name: Django Build, Tests and CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test: 
    # the operating system your job will run on
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  
      - uses: actions/setup-python@v3  
      - run: pip install -r requirements.txt  # install requirements to enable GitHub run our code
      - run: python manage.py test  # run the unit test
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-django-app:latest